app/Http/routes.php
Route::get('/category-priority/new', 'CategoryPriorityController@create');
Route::get('/category-priority/edit/{id}', 'CategoryPriorityController@edit');
Route::post('/category-priority', 'CategoryPriorityController@store');
Route::put('/category-priority/{id}', 'CategoryPriorityController@update');
Route::get('/category-priority/delete/{id}', 'CategoryPriorityController@destroy');
Route::post('/category-priority/update/requirement-order', 'CategoryPriorityController@updateRequirementOrder');

Route::post('/speciality-priority-set', 'SpecialityPrioritySetController@store');
Route::get('/speciality-priority-set/delete/{id}', 'SpecialityPrioritySetController@destroy');

Route::get('/priority-set/new', 'PrioritySetController@create');
Route::post('/priority-set', 'PrioritySetController@store');
Route::get('/priority-set/edit/{id}', 'PrioritySetController@edit');
Route::put('/priority-set/{id}', 'PrioritySetController@update');
Route::get('/priority-set/delete/{id}', 'PrioritySetController@destroy');

Route::get('/service-post-view', 'HomeController@servicePostView');
Route::post('/service-post-view', 'HomeController@servicePostView');
Route::get('/service-overview', 'ServiceOverviewController@index');
Route::post('/service-overview', 'ServiceOverviewController@index');
Route::post('/service-assign', 'ServiceOverviewController@assignService');
Route::put('/service-assign/update', 'ServiceOverviewController@updateAssignService');
Route::get('/service-overview/test', 'ServiceOverviewController@timeline');


Route::get('/colors', 'ColorController@index');
Route::get('/color/new', 'ColorController@create');
Route::get('/color/edit/{id}', 'ColorController@edit');
Route::post('/color', 'ColorController@store');
Route::put('/color/{id}', 'ColorController@update');
Route::get('/color/delete/{id}', 'ColorController@destroy');

Route::get('/transition-times', 'TransitionTimeController@index');
Route::get('/transition-time/new', 'TransitionTimeController@create');
Route::get('/transition-time/edit/{id}', 'TransitionTimeController@edit');
Route::post('/transition-time', 'TransitionTimeController@store');
Route::put('/transition-time/{id}', 'TransitionTimeController@update');
Route::get('/transition-time/delete/{id}', 'TransitionTimeController@destroy');
//Route::get('/service/{id}/requirement-view', 'ServiceOverviewController@testing');
//Route::post('/service/{id}/requirement-view', 'ServiceOverviewController@testing');

Route::get('/directorate-service/{id}/requirements', 'DirectorateServiceController@requirement');
Route::post('/directorate-service/requirement', 'DirectorateServiceController@storeRequirement');
Route::get('/directorate-service/requirement/delete/{id}', 'DirectorateServiceController@destroyRequirement');

Route::get('/service/{id}/requirements', 'ServiceController@requirement');
Route::post('/service/requirement', 'ServiceController@storeRequirement');
Route::get('/service/requirement/delete/{id}', 'ServiceController@destroyRequirement');
//Route::get('/servicepostdata', 'HomeController@servicePostData');
Route::get('service/get-requirement-data','ServiceController@getRequirementData');
Route::get('service/save-requirement-condition','ServiceController@saveRequirementCondition');
Route::get('service/delete-requirement-condition','ServiceController@deleteRequirementCondition');
Route::get('service/operator-type','ServiceController@operatorTypes')->name('operator-type');
Route::get('service/get-operatorby-parameter','ServiceController@getOperatorbyParameter')->name('get-operatorby-parameter');

Route::get('/getDirectorateRotaGroups/{id}', 'HomeController@getDirectorateRotaGroups');
Route::get('/getShiftTypeService/{d_id}/{s_id}/{c_id}/{sb_id}', 'HomeController@getShiftTypeService');
Route::get('/getServiceDropdown/{d_id}/{s_id}/{c_id}/{sb_id}', 'ServiceController@getServiceDropdown');
Route::get('/getDirectorateServiceDropdown/{d_id}/{c_id}/{sb_id}', 'DirectorateServiceController@getServiceDropdown');
Route::post('/set-date', 'HomeController@setDateInSession');
Route::post('/set-calender-date', 'HomeController@setCalenderDateInSession');
Route::get('/getValues/{value}/{d_id}', 'DirectorateServiceController@getValues');
Route::get('/getOperators/{type}', 'serviceController@operatorsWithType');
Route::get('/getAdditionalValues/{d_id}/{s_id}/{p_id}', 'PostController@getAdditionalParameter');
Route::get('/getCategoryPriority/{id}', 'CategoryPriorityController@getCategoryPriority');
Route::get('/getColorsCode', 'ColorController@getColorsCode');
Route::get('/searchSubcategory', 'SubCategoryController@searchSubcategory');
Route::get('/getCategoryTree/{id}', 'HomeController@getCategoryTree');
Route::get('/serviceTimeline', 'ServiceOverviewController@getServicesTimeline');
Route::get('/staffTimeline', 'ServiceOverviewController@getStaffTimeline');
Route::get('/getRequiremetByDateTime', 'ServiceOverviewController@getRequiremetByDateTime');

Route::get('/testing', 'ServiceOverviewController@testing');
Route::post('/testing', 'ServiceOverviewController@testing');
Route::get('/test', 'ServiceOverviewController@requirementData');
Route::get('/over-view', 'ServiceOverviewController@requirementData');



/*User Access Roles Routes Start Here*/
  Route::get('/user-roles', 'UserRolesController@index')->name('user-roles');
  Route::get('/user-roles/new', 'UserRolesController@create');
  Route::post('/user-roles', 'UserRolesController@store');
  Route::get('/user-roles/edit/{id}', 'UserRolesController@edit');

  Route::get('role/permissions/{id}','UserRolesController@rolePermissions')->name('permissions');
  Route::post('add-role-permissions','UserRolesController@storeRolePermissions')->name('add-role-permissions');


/*User Access Roles Routes End Here*/


/*Trust Signup Request Routes End Here*/

    Route::get('/trust-requests', 'SignupRequestController@getTrustRequests')->name('trust-requests');
    Route::post('/update-request', [
        'uses' => 'SignupRequestController@updateRequest'
    ]);

/*Trust Signup Request Routes End Here*/

    /*Email Templates Routes End Here*/

    Route::get('/email-templates', 'EmailTemplatesController@index')->name('email-templates');
    Route::get('/get-trust-template', 'EmailTemplatesController@getTrustTemplate');
    Route::get('/get-email-templates', 'EmailTemplatesController@getEmailTypeTemplate');
    Route::post('/update-template', 'EmailTemplatesController@updateTemplate')->name('create-new-template');
    Route::get('/create-new-template', 'EmailTemplatesController@createNewTemplate')->name('create-new-template');
    Route::post('/create-template', 'EmailTemplatesController@storeNewTemplate');

    /*Email Templates Routes End Here*/


    Route::post('/uploadEmailTemplateImage', 'HomeController@uploadEmailTemplateImage');


/*
 * paramete routes
 */
Route::resources(['service/requirement/parameter' => 'ServiceRequirementParameterController']);
/*
 * Operator routes
 */
Route::get('operator-index','OperatorController@index')->name('operator-index');
Route::get('operator-add','OperatorController@create')->name('operator-add');
Route::post('operator-store','OperatorController@store')->name('operator-store');
Route::get('operator-getParameter/{id}','OperatorController@getParameter')->name('operator-getParameter');

Route::get('condition','ServiceController@condition')->name('condition');
Route::post('condition','ServiceController@conditionPost')->name('condition');



Route::get('/command','CommandController@index');
Route::get('/optimal-assignment','CommandController@optimalAssignment');

Route::get('/account-security',function () {

    return view('account-security');
})->name('account-security');

/*
 * Email Verificaton middleware routes start
 */

Route::get('/email-verification-disable',function () {
    return view('email-code-verification.disable-code-verification');
})->name('email-verification-disable');
Route::post('/email-verification-disable','EmailLoginSecurityController@disableEmailCodeVerification')->name('email-verification-disable');
Route::get('/email-verification-enable','EmailLoginSecurityController@enableEmailCodeVerification')->name('email-verification-enable');

    /*
     * Email Verificaton middleware routes End
     */


/*
   * SMS Verificaton middleware routes start
  */

Route::get('/sms-verification-disable',function () {
        return view('sms-code-verification.disable-code-verification');
    })->name('sms-verification-disable');
Route::post('/sms-verification-disable','SmsLoginSecurityController@disableSmsCodeVerification')->name('sms-verification-disable');
Route::get('/sms-verification-enable','SmsLoginSecurityController@enableSmsCodeVerification')->name('sms-verification-enable');
    /*
       * SMS Verificaton middleware routes End

    */

    Route::get('/user-emails','HomeController@getUserEmails')->name('user-emails');

});


Route::get('/google-2f-authenticate','Google2FAuthenticator@show2faForm')->name('google-2f-authenticate');
Route::post('/generate2faSecret','Google2FAuthenticator@generate2faSecret')->name('generate2faSecret');
Route::post('/enable2fa','Google2FAuthenticator@enable2fa')->name('enable2fa');
Route::post('/disable2fa','Google2FAuthenticator@disable2fa')->name('disable2fa');
Route::post('/2faVerify', function () {
    App\Helpers\LoginAuthenticationHelper::updateLoginVerificationInLoginDetailTbl('googleApp');
    return redirect('/');
})->name('2faVerify')->middleware('2fa');


Route::post('/verify-email-code','EmailLoginSecurityController@verifyCode')->name('verify-email-code');
Route::get('/email-code-verification','EmailLoginSecurityController@emailCodeVerifcation')->name('email-code-verification');
Route::get('/send-email-verification-code','EmailLoginSecurityController@sendCode')->name('send-email-verification-code');

Route::post('/verify-sms-code','SmsLoginSecurityController@verifyCode')->name('verify-sms-code');

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Helpers;
use App\Http\Requests;
use GuzzleHttp\Client;

class OperatorController extends Controller {

    private $api_token, $api_url, $api_client;
    private $operators = [
            ['name' => 'Equal to', 'id' => '=', 'type' => 'integer'],
            ['name' => 'Greater or Equal to', 'id' => '>=', 'type' => 'integer'],
            ['name' => 'Greater than', 'id' => '>', 'type' => 'integer'],
            ['name' => 'Less or Equal to', 'id' => '<=', 'type' => 'integer'],
            ['name' => 'Less than', 'id' => '<', 'type' => 'integer'],
            ['name' => 'Not equal to', 'id' => '!=', 'type' => 'integer'],
            ['name' => 'Between', 'id' => 'between', 'type' => 'integer'],
            ['name' => 'Any', 'id' => 'any', 'type' => 'string'],
            ['name' => 'Is', 'id' => 'is', 'type' => 'string'],
            ['name' => 'Is not', 'id' => 'is_no', 'type' => 'string'],
    ];

    public function __construct() {
        $this->middleware('auth');
        $this->api_url = config('app.API_URL');
        if (auth()->user())
            $this->api_token = auth()->user()->api_token;
        else
            $this->api_token = '';
        $this->api_client = new Client(['headers' => ['Authorization' => 'Bearer ' . $this->api_token]]);
    }

    public function index(Request $request) {
        $response = $this->api_client->request("GET", Helpers::getAPIUrl('trust') . auth()->user()->trust_id . '/directorates');
        $directorates = json_decode($response->getBody()->getContents());

        $operators = Helpers::getDropDownData($this->operators);
        $types = ['ineger' => 'Integer', 'string' => 'String'];
        $heading = _('All Operators');
        return view('operator.index', ['heading' => $heading, 'types' => $types, 'operators' => $operators]);
    }

    public function create() {
        $response = $this->api_client->request("GET", Helpers::getAPIUrl('trust') . auth()->user()->trust_id . '/directorates');
        $directorates = json_decode($response->getBody()->getContents());
        $operators = Helpers::getDropDownData($this->operators);
        $directorates = Helpers::getDropDownData($directorates);
        $types = ['integer' => 'Integer', 'string' => 'String'];
        $heading = _('All Operators');
        return view('operator.create', ['heading' => $heading, 'types' => $types, 'operators' => $operators, 'directorates' => $directorates]);
    }

    public function store(Request $request) {
        $name ='' ;
        $operators = Helpers::getDropDownData($this->operators);
        foreach ($operators as $key => $value) {
            if($key == $request->value){
                $name = $value;
            }
        }
        if(!empty($name)){
        $request->merge(['name' => $name]);
        $response = $this->api_client->request("post", Helpers::getAPIUrl('service') . 'operator/test', ['form_params' => $request->all()]);
        $parameters = json_decode($response->getBody()->getContents());
        return redirect(route('operator-index'));
        }
        return redirect()->back();
    }

    public function getParameter($id) {
        $response = $this->api_client->request("GET", Helpers::getAPIUrl('service') . 'requirement/get-parameter/test/' . $id);
        $parameters = json_decode($response->getBody()->getContents());
        $parameters = Helpers::getDropDownData($parameters);
        return response($parameters);
    }

}

resources/views/operator/create.blade.php
@extends('admin.admin')

@section('extra-css')
<link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{url('/css/custom.css')}}" rel="stylesheet" type="text/css" />
<link href="{{url('/css/service-requirement.css')}}" rel="stylesheet" type="text/css" />
<style>
    .value-2{
        display: none;
    }
</style>
@endsection
@php $red_count = $orange_count = $yellow_count = $green_count = $blue_count = 1 ; @endphp
@section('content')
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title col-md-6">
                <h1<i class="fa fa-life-bouy fa-2x"></i> {!!  $heading !!}</h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            @if (Illuminate\Support\Facades\Session::has('success-parameters'))
            <div class='alert alert-success alert-dismissible' role='alert'>
                <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                <ul>
                    <li>
                        {{Session('success-parameters')}}
                    </li>
                </ul>
            </div>
            @elseif (Illuminate\Support\Facades\Session::has('error-parameters'))
            <div class='alert alert-danger alert-dismissible' role='alert'>
                <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                {{ session('error-parameters') }}
            </div>
            @endif

            <div class="col-md-12 col-sm-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    {!! Form::open(['method' => 'post', 'url' => 'operator-store']) !!}
                    <div class="form-group ">
                        {!! Form::label('Directorates', 'Directorates', ['class' => 'awesome']) !!}
                        {!! Form::select('directorate_id',$directorates,'', [ 'class'=>'form-control directorate_id']) !!}
                    </div>
                    <div class="form-group ">
                        {!! Form::label('Operator', 'Operator', ['class' => 'awesome']); !!}
                        {!! Form::select('value',$operators,'', [ 'class'=>'form-control parameter']) !!}
                    </div>
                                        <div class="form-group checkboxs">
                                     </div>
                   
                    <div class="form-group ">
                        {!! Form::label('Type', 'Type', ['class' => 'awesome']); !!}
                        {!! Form::select('type',$types,'', [ 'class'=>'form-control']) !!}
                    </div>
                    <div class="form-group ">
                        <input class="btn green" type="submit" value="Add !"/>     
                        <a  href="{!!  route('service.requirement.parameter.index') !!}">
                            <button id="sample_editable_1_2_new" class="btn sbold green" > Back <i class="fa fa-backward"></i></button>
                        </a>
                    </div>


                    {!! Form::close() !!}

                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE BASE CONTENT -->
    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
@endsection

@section('extra-js')
            <!--<script src="{{url('/js/service-requirement.js')}}" type="text/javascript"></script>-->
<script>
    $('.directorate_id').on('change', function () {
        var values = '';
        var directorate_id = $(".directorate_id option:selected").val();
        var send = {directorate_id: directorate_id};
            jQuery.ajaxSetup({async: false});
            var responseData;
            var url = APP_URL + '/operator-getParameter/'+directorate_id;
            $.get(url,  function (data) {
                responseData = data;
            });
            $.each(responseData, function (index, value) {
                 values +=  '<span style="display: inline-block;  margin-left: 10px;"><lable>'+value+'</lable>  <input type="checkbox" class = "checkbox"id="check_all_1" name="parameters[]" title="Select All" value="'+index+'"/></span>';
            });
//            $(".parameter-select").empty().append(values);
            $(".checkboxs").empty().append(values);
            $(".checkboxs").show();

       
    });
</script>
@endsection

resources/views/operator/edit.blade.php
@extends('admin.admin')

@section('extra-css')
<link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{url('/css/custom.css')}}" rel="stylesheet" type="text/css" />
<link href="{{url('/css/service-requirement.css')}}" rel="stylesheet" type="text/css" />
<style>
    .value-2{
        display: none;
    }
</style>
@endsection
@php $red_count = $orange_count = $yellow_count = $green_count = $blue_count = 1 ; @endphp
@section('content')
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title col-md-6">
                <h1<i class="fa fa-life-bouy fa-2x"></i> {!!  $heading !!}</h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            @if (Illuminate\Support\Facades\Session::has('success-requirement'))
            <div class='alert alert-success alert-dismissible' role='alert'>
                <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                <ul>
                    <li>
                        {{Session('success-requirement')}}
                    </li>
                </ul>
            </div>
            @endif
            <div class="col-md-12 col-sm-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    {!! Form::open(['method' => 'put', 'action' => ['ServiceRequirementParameterController@update',$id]]) !!}
<!--                    <div class="form-group ">
                        {!! Form::label('parameter', 'Parameter', ['class' => 'awesome']) !!}
                        {!! Form::select('directorate_id', $directorates ,$directorates , [ 'class'=>'form-control']) !!}
                    </div>-->
                    <div class="form-group ">
                        {!! Form::label('Parameter', 'Parameter', ['class' => 'awesome']); !!}
                        {!! Form::select('name', $parameterDropdown,$parameterDropdown,['placeholder' => 'Parameter Name' , 'class' => 'form-control','required']); !!}
                    </div>
                    <div class="form-group ">
                        {!! Form::label('Type', 'Type', ['class' => 'awesome']); !!}
                        {!! Form::select('type', $type , $typeSelectet , [ 'class'=>'form-control']) !!}
                    </div>
                   <div class="form-group ">
                       <input class="btn green" type="submit" value="Add !" title="Update Value"/>     
                        <a  href="{!!  route('service.requirement.parameter.index') !!}" >
                            <button id="sample_editable_1_2_new" class="btn sbold green" title="Back to home"> Back <i class="fa fa-backward"></i></button>
                        </a>
                    </div>

                    {!! Form::close() !!}
                </div>


                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE BASE CONTENT -->
    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
@endsection

@section('extra-js')
<!--<script src="{{url('/js/service-requirement.js')}}" type="text/javascript"></script>-->
@endsection

resources/views/operator/index.blade.php
@extends('admin.admin')

@section('extra-css')
<link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{url('/css/custom.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Manage Services</h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">

                    
                    @if (Illuminate\Support\Facades\Session::has('success-service'))
                    <div class='alert alert-success alert-dismissible' role='alert'>
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                        {{ session('success-service') }}
                    </div>
                    @elseif (Illuminate\Support\Facades\Session::has('error-service'))
                    <div class='alert alert-danger alert-dismissible' role='alert'>
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                        {{ session('error-service') }}
                    </div>
                    @endif

                    @if (Illuminate\Support\Facades\Session::has('service-add'))
                    <div class='alert alert-success alert-dismissible' role='alert'>
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                        {{ session('service-add') }}
                    </div>
                    @elseif(Illuminate\Support\Facades\Session::has('service-teamplate-deleted'))
                    <div class='alert alert-danger alert-dismissible' role='alert'>
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                        {{ session('service-teamplate-deleted') }}
                    </div>
                    @endif
                    <div class="portlet-body">
                        <div class="table-toolbar">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="btn-group">
                                        <a href="{!!  route('operator-add') !!}">
                                            <button id="sample_editable_1_2_new" class="btn sbold green" > Add New <i class="fa fa-plus"></i></button>
                                        </a>
                                    </div>
                                </div>
                            
                            </div>
                        </div>
            
                        <div class="tab-content">
                     
                                  
                                    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_3">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Contactable</th>
                                                <th>Min Standards</th>
                                                <th> Actions</th>
                                            </tr>
                                        </thead>
 
                                        <tbody>
                                        </tbody>
                                    </table>
                                
                        </div>
                    </div>
                </div>
      
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE BASE CONTENT -->
    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
@endsection
@section('modal')
<div class="modal fade bs-modal-sm" id="small" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Delete Confirmation</h4>
            </div>
            <div class="modal-body"> You want to delete this record? </div>
            <div class="modal-footer">
                <a href="" id='delete-button'><button type="submit" class="btn btn-danger" >Delete</button></a>
                <button type="button" class="btn green" data-dismiss="modal">Cancel</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection

@section('extra-js')
@include('includes.scriptsViewLinks')
<script src="{{url('/js/checkbox_update.js')}}"></script>
<script>
$(document).ready(function () {
    $('.delete').click(function () {
        id = $(this).attr('id').split('-');
        if (id[0] == 'd') {
            url = '{{url("/directorate-service/delete")}}' +'/'+ id[1];
        } else {
            url = '{{url("/service/delete")}}' +'/'+ id[1];
        }
        $('#delete-button').attr('href', url);
//        $('#delete-button').attr('href', '/service/delete/' + $(this).attr('id'));
    });
    $("#directorate_speciality_id,#directorate").change(function () {
        $("form").submit();
    });
//        $('.main-check-box .check-boxes').change(function () {
//            $(this).parent().find('.sub-category').toggleClass('hide');
//        });
});

</script>
@endsection